spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 2MB
server:
  port: 8888
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      id-type: auto
    banner: false
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: cn.tqktqk.work.problemreportingsystem.dao.typehandler